# Generated by Django 4.2.7 on 2024-01-15 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_workplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='working_days',
            field=models.ManyToManyField(to='coach.workingday'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_ratings', to='coach.trainer'),
        ),
        migrations.DeleteModel(
            name='WorkPlan',
        ),
    ]
