# Generated by Django 4.2.7 on 2024-01-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_trainer_average_rating_trainer_number_of_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='working_days',
        ),
        migrations.DeleteModel(
            name='WorkingDay',
        ),
    ]
