# Generated by Django 4.2.7 on 2024-01-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_remove_trainer_working_days_delete_workingday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='number_of_votes',
        ),
    ]
