# Generated by Django 4.2.7 on 2024-01-14 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_meal', models.CharField(max_length=255)),
                ('meal_number', models.PositiveIntegerField(choices=[(1, 'Śniadanie'), (2, 'Drugie śniadanie'), (3, 'Obiad'), (4, 'Podwieczorek'), (5, 'Kolacja')])),
                ('hour', models.TimeField()),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('carbs', models.PositiveIntegerField()),
                ('fats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')])),
                ('meals', models.ManyToManyField(to='diet.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_diet', models.CharField(max_length=255)),
                ('description_diet', models.TextField()),
                ('calories_total', models.PositiveIntegerField()),
                ('protein_total', models.PositiveIntegerField()),
                ('carbs_total', models.PositiveIntegerField()),
                ('fats_total', models.PositiveIntegerField()),
                ('dishes', models.ManyToManyField(to='diet.dishes')),
                ('trainer_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diets_trainer', to='coach.trainer')),
                ('user_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diets_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
