# Generated by Django 4.2.7 on 2024-01-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='recipe',
            field=models.TextField(default='Brak przepisu'),
        ),
    ]
