# Generated by Django 4.2.7 on 2024-01-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_alter_meal_meal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_number',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('second_breakfast', 'Second breakfast'), ('lunch', 'Lunch'), ('afternoon_snack', 'Afternoon snack'), ('dinner', 'Dinner')], max_length=100),
        ),
    ]
