# Generated by Django 4.2.7 on 2024-01-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_alter_meal_meal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100),
        ),
    ]
