# Generated by Django 4.2.7 on 2024-01-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_alter_dishes_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='calories_total',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='carbs_total',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='fats_total',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='protein_total',
        ),
    ]
