# Generated by Django 4.2.7 on 2024-01-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_remove_dishes_calories_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='calories_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dishes',
            name='carbs_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dishes',
            name='fats_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dishes',
            name='protein_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
