# Generated by Django 4.2.7 on 2024-01-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0008_dishes_calories_total_dishes_carbs_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='description_diet',
            field=models.TextField(default=''),
        ),
    ]
