# Generated by Django 4.2.7 on 2024-01-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0009_diet_description_diet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='calories_total',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='carbs_total',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='fats_total',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='protein_total',
        ),
    ]
