# Generated by Django 4.2.7 on 2024-01-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0010_remove_dishes_calories_total_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diet',
        ),
    ]
