# Generated by Django 4.2.7 on 2024-01-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0011_delete_diet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dishes',
        ),
    ]
