# Generated by Django 4.2.7 on 2024-01-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0014_diet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='trainer_added',
            new_name='trainer',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='user_added',
            new_name='user',
        ),
    ]
