# Generated by Django 4.2.7 on 2024-01-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='day',
            new_name='date',
        ),
        migrations.AddField(
            model_name='healthissue',
            name='reason',
            field=models.CharField(default='', max_length=250),
        ),
    ]
