# Generated by Django 4.2.7 on 2024-01-15 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_remove_trainer_working_days_delete_workingday'),
        ('meet', '0002_rename_day_reservation_date_healthissue_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkingDay', models.ManyToManyField(to='meet.workingday')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.trainer')),
            ],
        ),
    ]
