# Generated by Django 4.2.7 on 2024-01-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_workingday_workplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingday',
            name='start_time',
        ),
    ]
