# Generated by Django 4.2.7 on 2024-01-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_workingday_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
