# Generated by Django 4.2.7 on 2024-01-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_alter_workingday_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingday',
            name='start_time',
        ),
    ]
