# Generated by Django 4.2.7 on 2024-01-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0008_workingday_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workplan',
            old_name='WorkingDay',
            new_name='working_days',
        ),
    ]
