# Generated by Django 4.2.7 on 2024-01-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0009_rename_workingday_workplan_working_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthIssue',
        ),
    ]
