# Generated by Django 4.2.7 on 2024-01-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='set_reps',
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='set',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='url_exercise',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
