# Generated by Django 4.2.7 on 2024-01-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_remove_exercise_set_reps_exercise_reps_exercise_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.PositiveIntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='set',
            field=models.PositiveIntegerField(default=0, max_length=100),
        ),
    ]
