# Generated by Django 4.2.7 on 2024-01-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_alter_exercise_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='set',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
