# Generated by Django 4.2.7 on 2024-01-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_alter_exercise_reps_alter_exercise_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
