# Generated by Django 4.2.7 on 2024-01-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_alter_trainingplan_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='goal',
            field=models.CharField(max_length=100),
        ),
    ]
