# Generated by Django 4.2.7 on 2024-01-15 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coach', '0003_workplan'),
        ('plan', '0013_rename_set_exercise_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('date_verified', models.DateField(blank=True, null=True)),
                ('completed_exercises', models.ManyToManyField(blank=True, to='plan.exercise')),
                ('exercise_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.exerciseset')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
